server:
  port: 8001

mybatis:
#  这里有坑： configlocation 和configuration 不能同时开启，否则启动会失败
#  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.sunrise.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


spring:
  application:
    name: microservice-cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200