server:
  port: 3344

spring:
  application:
    name:  microservice-cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lzhaoyang/sunrise-bootcloud-config.git  #GitHub上面的git仓库名字
#security:
#  basic:
#    enabled: true
#  user:
#    name: root
#    password: 123456
